# src/nlp/ollama_conversation.py
#
# Design principles:
#   • State tracking is done SERVER-SIDE (reliable regex extraction).
#     The LLM's ONLY job is to ask for missing info in natural language.
#   • Recommendations fire as soon as the server has all three pieces.
#     The recommendation intro is HARDCODED — no LLM call, no hallucination.
#   • After recommendations the session immediately resets so the user
#     can start a new search without any mode-switching logic.
#   • Sentinel JSON extraction is removed — it was a potential injection
#     vector and is redundant since all extraction is server-side.
#   • Async-first: httpx.AsyncClient so FastAPI never blocks.

import logging
import re
from datetime import datetime
from typing import Optional

import httpx

from config import Config
from src.recommendations.engine import recommend_courses

logger = logging.getLogger(__name__)


# ── Fixed strings — never generated by the LLM ───────────────────────────────

_GREETING = (
    "Hi, I'm Genevieve, your AI learning advisor. "
    "To recommend the right courses for you, I need three things: "
    "what you want to learn, your experience level — beginner, intermediate, or advanced — "
    "and your career goal. Please go ahead."
)

# Spoken the moment all three pieces are collected and recs are ready.
# Hardcoded so the LLM cannot hallucinate course names or fabricate facts.
_REC_INTRO = (
    "Your personalised course recommendations are ready — take a look below."
)

# Spoken immediately after recommendations, inviting a new search.
_POST_REC_BRIDGE = (
    "If you'd like to explore a different topic, just tell me what you want to learn next."
)


# ── System prompt ─────────────────────────────────────────────────────────────
#
# Single, strict prompt. There is no "chatting" variant — after
# recommendations the session resets and this same prompt is reused.

_SYSTEM_PROMPT = """You are Genevieve, a voice learning advisor. Collect goal, level, and career — then the system finds courses automatically.

RULES:
1. ONE sentence only (spoken aloud by TTS — keep it short and natural).
2. Acknowledge what the user just said, then ask for what is STILL NEEDED.
3. Ask for ALL missing items in that one sentence.
4. Never re-ask for things already collected.
5. No filler words: no "Great!", "Sure!", "Of course!".
6. Never name any course, platform, or tool.
7. Off-topic input (jokes, weather): "I'm here to match you with courses — what would you like to learn?"

EXAMPLE RESPONSES (match this style exactly):
• All three missing:  "What would you like to learn, what's your experience level, and what career are you working toward?"
• Goal just given:    "What's your experience level — beginner, intermediate, or advanced — and what's your career goal?"
• Goal + level given: "And what career are you aiming for?"
• Level just given:   "What would you like to learn, and what's your target career?"
• Career just given:  "What would you like to learn, and what's your experience level?"
"""


def _build_system_prompt(collected: dict) -> str:
    """
    Append context-aware state to the strict system prompt so the LLM
    knows exactly what is already known and what is still missing.
    """
    prompt = _SYSTEM_PROMPT

    known = {k: v for k, v in collected.items() if v}
    missing = [k for k in ("goal", "level", "career") if not collected.get(k)]

    if known:
        parts = []
        if collected.get("goal"):   parts.append(f"goal = {collected['goal']}")
        if collected.get("level"):  parts.append(f"level = {collected['level']}")
        if collected.get("career"): parts.append(f"career = {collected['career']}")
        prompt += f"\n\nALREADY COLLECTED — do NOT ask again: {'; '.join(parts)}."

    if missing:
        labels = {
            "goal":   "what they want to learn",
            "level":  "their experience level (beginner / intermediate / advanced)",
            "career": "their target job or career goal",
        }
        missing_str = " and ".join(labels[k] for k in missing)
        prompt += (
            f"\n\nSTILL NEEDED: {missing_str}."
            f"\n\nYOUR RESPONSE: Write exactly ONE sentence asking for {missing_str}."
            "\nDo NOT say you are here to help. Do NOT trigger rule 7. Just ask the question."
        )

    return prompt


# ── Server-side intent extraction ─────────────────────────────────────────────
# All information is extracted here using regex — the LLM is never
# trusted to output structured data.

_LEVEL_RE = {
    "beginner": re.compile(
        r"\b(beginner|new to|just start(ed|ing)?|no experience|starting out|"
        r"never (used|done|tried)|newbie|novice|zero knowledge|complete(ly)? new|"
        r"first time|brand new|from scratch|entry.?level|just (learning|getting started)|"
        r"haven.t (used|done|tried)|no (idea|background|clue))\b",
        re.I,
    ),
    "intermediate": re.compile(
        r"\b(intermediate|some experience|familiar (with)?|know a (bit|little)|"
        r"been (using|working with)|used before|working knowledge|some background|"
        r"comfortable with|worked with|hands.on|moderate(ly)?|decent (knowledge|grasp)|"
        r"self.taught|few months|couple (of )?(months|years)|few years|some coding|"
        r"some programming)\b",
        re.I,
    ),
    "advanced": re.compile(
        r"\b(advanced|expert|experienced|senior|professional|proficient|"
        r"years of|deep knowledge|strong background|extensive|multiple years|"
        r"many years|mastered|lead (dev|engineer)|principal|production experience|"
        r"[0-9]+ years)\b",
        re.I,
    ),
}

_GOAL_PATTERNS = [
    (re.compile(r"\b(python|django|flask|fastapi|pandas|numpy)\b", re.I),        "Python"),
    (re.compile(r"\b(machine learning|deep learning|\bml\b|\bai\b|neural|nlp|"
                r"llm|generative ai|pytorch|tensorflow|keras|computer vision|"
                r"artificial intelligence)\b", re.I),                            "machine learning"),
    (re.compile(r"\b(web dev(elopment)?|html|css|javascript|typescript|react|"
                r"next\.?js|node\.?js|vue|angular|svelte|frontend|front.end|"
                r"web design|build (websites?|web apps?)|fullstack|full.?stack|"
                r"back.?end)\b", re.I),                                           "web development"),
    (re.compile(r"\b(data science|data analy(sis|tics)|tableau|power bi|"
                r"statistics|statistical|visualization|reporting)\b", re.I),     "data science"),
    (re.compile(r"\b(sql|database|postgres|mysql|mongodb|sqlite|oracle|"
                r"database design|relational|queries?)\b", re.I),                "SQL"),
    (re.compile(r"\b(devops|docker|kubernetes|k8s|ci.?cd|cloud|aws|gcp|azure|"
                r"terraform|ansible|microservices|infrastructure|containeriz)\b", re.I), "DevOps"),
    (re.compile(r"\b(java\b|spring boot|j2ee|maven|gradle)\b", re.I),           "Java"),
    (re.compile(r"\b(excel|spreadsheet|vba|pivot table|macros?|financial model)\b", re.I), "Excel"),
    (re.compile(r"\b(data engineer(ing)?|etl|apache spark|hadoop|data pipeline|"
                r"data warehouse|data lake)\b", re.I),                           "data engineering"),
    (re.compile(r"\b(cyber.?security|ethical hack(ing)?|penetration test(ing)?|"
                r"pentesting|infosec|network security)\b", re.I),               "cybersecurity"),
    (re.compile(r"\b(mobile (dev(elopment)?|app)|ios|android|swift|kotlin|"
                r"flutter|react native)\b", re.I),                               "mobile development"),
    # General programming — catch-all for "coding", "programming", "build apps"
    (re.compile(r"\b(programming|coding|build (apps?|software|systems?)|"
                r"software development|computer science)\b", re.I),              "programming"),
]

_CAREER_PATTERNS = [
    (re.compile(r"\b(data scientist)\b", re.I),                        "data scientist"),
    (re.compile(r"\b(data analyst)\b", re.I),                          "data analyst"),
    (re.compile(r"\b(data engineer)\b", re.I),                         "data engineer"),
    (re.compile(r"\b(software engineer|software developer)\b", re.I),  "software engineer"),
    (re.compile(r"\b(web developer|full.?stack|back.?end)\b", re.I),   "web developer"),
    (re.compile(r"\b(frontend developer|front.end)\b", re.I),          "frontend developer"),
    (re.compile(r"\b(devops engineer|sre|cloud engineer)\b", re.I),    "DevOps engineer"),
    (re.compile(r"\b(product manager|\bpm\b)\b", re.I),                "product manager"),
    (re.compile(r"\b(business analyst)\b", re.I),                      "business analyst"),
    (re.compile(r"\b(ml engineer|machine learning engineer)\b", re.I), "ML engineer"),
    # Catch-all for standalone "developer", "programmer", "coder"
    (re.compile(r"\b(developer|programmer|coder|software dev)\b", re.I), "software engineer"),
]


def _extract_info(text: str) -> dict:
    """
    Extract goal / level / career from a single user message using regex.
    Returns only the keys that were found (never overwrites with None).
    """
    found: dict = {}

    for label, pattern in _LEVEL_RE.items():
        if pattern.search(text):
            found["level"] = label
            break

    for pattern, goal in _GOAL_PATTERNS:
        if pattern.search(text):
            found["goal"] = goal
            break

    for pattern, career in _CAREER_PATTERNS:
        if pattern.search(text):
            found["career"] = career
            break

    return found


# ── Conversation manager ───────────────────────────────────────────────────────

class OllamaConversationManager:
    """
    Manages per-session conversation state and communicates with Ollama.

    Pipeline (strict):
      1.  Greeting    — hardcoded, no LLM
      2.  Collecting  — LLM asks for missing info; server extracts values
      3.  Recommend   — hardcoded intro + recommendation engine; session resets
      4.  (back to 2) — user can immediately start a new search
    """

    def __init__(self):
        self.sessions: dict = {}
        self.base_url = Config.OLLAMA_BASE_URL
        self.model    = Config.OLLAMA_MODEL
        self.timeout  = Config.OLLAMA_TIMEOUT

    # ── Public API ────────────────────────────────────────────────────────────

    def new_session(self, session_id: str) -> dict:
        self.sessions[session_id] = {
            "session_id": session_id,
            "messages":   [],
            "collected":  {"goal": None, "level": None, "career": None},
            "created_at": datetime.now().isoformat(),
        }
        logger.info(f"New session: {session_id}")
        return self.sessions[session_id]

    async def process_message(self, session_id: str, user_text: str) -> dict:
        """
        Process one user turn.

        Returns:
          {
            "text":            str   — spoken response
            "action":          "continue" | "recommend"
            "collected_info":  dict
            "recommendations": list  — populated only when action=="recommend"
          }
        """
        if session_id not in self.sessions:
            self.new_session(session_id)

        session   = self.sessions[session_id]
        collected = session["collected"]

        # ── Step 1: Hardcoded greeting — zero LLM risk ────────────────────
        if user_text == "__init__":
            return {
                "text":            _GREETING,
                "action":          "continue",
                "collected_info":  collected,
                "recommendations": [],
            }

        # ── Step 2: Server-side extraction ────────────────────────────────
        # Extract goal / level / career from what the user just said.
        # Allow correction: if user explicitly contradicts a stored value
        # (e.g. "actually I'm advanced"), overwrite.  Otherwise never overwrite
        # so a garbled Whisper transcription can't corrupt known good values.
        extracted = _extract_info(user_text)
        correction_words = re.search(r"\b(actually|no|wait|sorry|correction|i meant|i mean)\b", user_text, re.I)
        for key, val in extracted.items():
            if val and (not collected.get(key) or correction_words):
                collected[key] = val
                logger.info(f"[{session_id}] Extracted {key}={val!r}")

        # Add user turn to history (used as context for the LLM)
        session["messages"].append({"role": "user", "content": user_text})
        if len(session["messages"]) > Config.MAX_HISTORY:
            session["messages"] = session["messages"][-Config.MAX_HISTORY:]

        # ── Step 3: All three collected → recommend immediately ───────────
        if all(collected.get(k) for k in ("goal", "level", "career")):
            recs = recommend_courses(
                goal   = collected["goal"],
                level  = collected["level"],
                career = collected["career"],
            )
            triggered_by = dict(collected)
            logger.info(
                f"[{session_id}] Recommending for "
                f"goal={triggered_by['goal']!r} "
                f"level={triggered_by['level']!r} "
                f"career={triggered_by['career']!r}"
            )

            # Reset state so next message starts fresh collection.
            # Clear message history so old goal/level/career context doesn't
            # bleed into the next search. Keep only the rec-intro as context.
            session["collected"] = {"goal": None, "level": None, "career": None}
            session["messages"] = [{"role": "assistant", "content": _REC_INTRO}]

            return {
                "text":            _REC_INTRO,
                "action":          "recommend",
                "collected_info":  triggered_by,
                "recommendations": recs,
            }

        # ── Step 4: Ask for missing info via LLM ──────────────────────────
        system = _build_system_prompt(collected)
        reply  = await self._call_ollama(session["messages"], system=system)
        logger.debug(f"[{session_id}] Ollama: {reply!r}")

        session["messages"].append({"role": "assistant", "content": reply})

        return {
            "text":            reply,
            "action":          "continue",
            "collected_info":  collected,
            "recommendations": [],
        }

    def get_session(self, session_id: str) -> Optional[dict]:
        return self.sessions.get(session_id)

    def delete_session(self, session_id: str) -> bool:
        if session_id in self.sessions:
            del self.sessions[session_id]
            return True
        return False

    # ── Private ───────────────────────────────────────────────────────────────

    async def _call_ollama(self, messages: list, system: str = _SYSTEM_PROMPT) -> str:
        payload = {
            "model":    self.model,
            "messages": [{"role": "system", "content": system}] + messages,
            "stream":   False,
            "options": {
                "temperature": 0.2,    # Very low — maximise instruction-following
                "num_predict": 120,    # Allow up to ~one sentence of tokens
                # NOTE: do NOT use stop=["\n",".",…] — it strips terminal
                # punctuation (stops AT the char without including it), so
                # "What do you want to learn?" becomes "What do you want to
                # learn" → code appends "." → question becomes statement.
                # Instead, extract the first sentence below.
            },
        }
        try:
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                resp = await client.post(f"{self.base_url}/api/chat", json=payload)
                resp.raise_for_status()
                raw = resp.json()["message"]["content"].strip()
                # Extract the first complete sentence, preserving its own
                # terminal punctuation (. ? !).  If nothing matches (no
                # sentence-ending punctuation), fall back to adding ".".
                m = re.match(r'(.+?[.?!])', raw, re.DOTALL)
                if m:
                    raw = m.group(1).strip()
                elif raw and raw[-1] not in ".?!":
                    raw += "."
                return raw
        except httpx.ConnectError:
            logger.error("Ollama not reachable — is `ollama serve` running?")
            return "I'm having a little trouble — please try again in a moment."
        except Exception as exc:
            logger.exception(f"Ollama call failed: {exc}")
            return "Something went wrong. Please try again."
