# src/recommendations/courses.py
# Course catalog — local JSON-based, no external DB needed

COURSE_CATALOG = [
    # ── Python ──────────────────────────────────────────────────────────────
    {
        "id": "py-001",
        "title": "Python for Everybody",
        "provider": "Coursera / University of Michigan",
        "topics": ["python", "programming", "basics"],
        "level": "beginner",
        "careers": ["software engineer", "data analyst", "data scientist"],
        "duration": "8 weeks",
        "rating": 4.8,
        "description": "Learn Python from scratch — variables, loops, functions, and working with data.",
        "url": "https://www.coursera.org/specializations/python",
    },
    {
        "id": "py-002",
        "title": "Complete Python Bootcamp: Zero to Hero",
        "provider": "Udemy",
        "topics": ["python", "programming", "oop", "decorators"],
        "level": "beginner",
        "careers": ["software engineer", "backend developer"],
        "duration": "22 hours",
        "rating": 4.7,
        "description": "Comprehensive Python course covering beginner to advanced topics with 100+ exercises.",
        "url": "https://www.udemy.com/course/complete-python-bootcamp/",
    },
    {
        "id": "py-003",
        "title": "Python for Data Analysis",
        "provider": "DataCamp",
        "topics": ["python", "pandas", "numpy", "data analysis"],
        "level": "intermediate",
        "careers": ["data analyst", "data scientist"],
        "duration": "4 hours",
        "rating": 4.6,
        "description": "Master pandas and NumPy for real-world data manipulation and analysis.",
        "url": "https://www.datacamp.com/courses/data-manipulation-with-pandas",
    },
    {
        "id": "py-004",
        "title": "Advanced Python: Concurrency, Design Patterns & More",
        "provider": "Udemy",
        "topics": ["python", "asyncio", "design patterns", "performance"],
        "level": "advanced",
        "careers": ["software engineer", "backend developer"],
        "duration": "16 hours",
        "rating": 4.5,
        "description": "Deep dive into Python internals, async programming, and professional patterns.",
        "url": "https://www.udemy.com/course/advanced-python/",
    },

    # ── JavaScript ──────────────────────────────────────────────────────────
    {
        "id": "js-001",
        "title": "The Complete JavaScript Course 2024",
        "provider": "Udemy",
        "topics": ["javascript", "js", "programming", "web"],
        "level": "beginner",
        "careers": ["web developer", "frontend developer", "full stack developer"],
        "duration": "69 hours",
        "rating": 4.7,
        "description": "The most complete JS course — from basics to expert, includes modern ES6+.",
        "url": "https://www.udemy.com/course/the-complete-javascript-course/",
    },
    {
        "id": "js-002",
        "title": "JavaScript: Understanding the Weird Parts",
        "provider": "Udemy",
        "topics": ["javascript", "closures", "prototypes", "scope"],
        "level": "intermediate",
        "careers": ["web developer", "frontend developer"],
        "duration": "11.5 hours",
        "rating": 4.7,
        "description": "Deep dive into JavaScript engine, closures, prototypal inheritance, and more.",
        "url": "https://www.udemy.com/course/understand-javascript/",
    },

    # ── Data Science ────────────────────────────────────────────────────────
    {
        "id": "ds-001",
        "title": "IBM Data Science Professional Certificate",
        "provider": "Coursera / IBM",
        "topics": ["data science", "python", "sql", "machine learning", "visualization"],
        "level": "beginner",
        "careers": ["data scientist", "data analyst"],
        "duration": "5 months",
        "rating": 4.6,
        "description": "10-course professional certificate covering the full data science workflow.",
        "url": "https://www.coursera.org/professional-certificates/ibm-data-science",
    },
    {
        "id": "ds-002",
        "title": "Data Science Specialization",
        "provider": "Coursera / Johns Hopkins",
        "topics": ["data science", "r", "statistics", "machine learning"],
        "level": "intermediate",
        "careers": ["data scientist", "data analyst", "research scientist"],
        "duration": "11 months",
        "rating": 4.5,
        "description": "10-course specialization covering statistics, R, and reproducible research.",
        "url": "https://www.coursera.org/specializations/jhu-data-science",
    },
    {
        "id": "ds-003",
        "title": "Applied Data Science with Python",
        "provider": "Coursera / University of Michigan",
        "topics": ["data science", "python", "pandas", "matplotlib", "sklearn"],
        "level": "intermediate",
        "careers": ["data scientist", "data analyst"],
        "duration": "5 months",
        "rating": 4.4,
        "description": "5-course specialization applying Python tools to real data science problems.",
        "url": "https://www.coursera.org/specializations/data-science-python",
    },

    # ── Machine Learning / AI ───────────────────────────────────────────────
    {
        "id": "ml-001",
        "title": "Machine Learning Specialization",
        "provider": "Coursera / DeepLearning.AI",
        "topics": ["machine learning", "ai", "regression", "classification", "neural networks"],
        "level": "beginner",
        "careers": ["machine learning engineer", "data scientist", "ai engineer"],
        "duration": "3 months",
        "rating": 4.9,
        "description": "Andrew Ng's updated ML specialization — the best starting point for ML.",
        "url": "https://www.coursera.org/specializations/machine-learning-introduction",
    },
    {
        "id": "ml-002",
        "title": "Deep Learning Specialization",
        "provider": "Coursera / DeepLearning.AI",
        "topics": ["deep learning", "neural networks", "cnn", "rnn", "tensorflow"],
        "level": "intermediate",
        "careers": ["machine learning engineer", "ai engineer", "research scientist"],
        "duration": "5 months",
        "rating": 4.9,
        "description": "5-course deep learning specialization by Andrew Ng — CNNs, RNNs, and more.",
        "url": "https://www.coursera.org/specializations/deep-learning",
    },
    {
        "id": "ml-003",
        "title": "Practical Deep Learning for Coders",
        "provider": "fast.ai",
        "topics": ["deep learning", "pytorch", "fastai", "computer vision", "nlp"],
        "level": "intermediate",
        "careers": ["machine learning engineer", "ai engineer"],
        "duration": "14 weeks",
        "rating": 4.8,
        "description": "Top-down practical approach to deep learning — build real models fast.",
        "url": "https://course.fast.ai",
    },
    {
        "id": "ml-004",
        "title": "MLOps Specialization",
        "provider": "Coursera / DeepLearning.AI",
        "topics": ["mlops", "machine learning", "deployment", "monitoring", "pipelines"],
        "level": "advanced",
        "careers": ["mlops engineer", "machine learning engineer"],
        "duration": "4 months",
        "rating": 4.7,
        "description": "Deploy, monitor, and maintain ML models in production at scale.",
        "url": "https://www.coursera.org/specializations/machine-learning-engineering-for-production-mlops",
    },

    # ── Web Development ─────────────────────────────────────────────────────
    {
        "id": "web-001",
        "title": "The Web Developer Bootcamp 2024",
        "provider": "Udemy",
        "topics": ["web development", "html", "css", "javascript", "node", "mongodb"],
        "level": "beginner",
        "careers": ["web developer", "full stack developer", "frontend developer"],
        "duration": "74 hours",
        "rating": 4.7,
        "description": "Full stack bootcamp — HTML, CSS, JS, Node.js, Express, MongoDB.",
        "url": "https://www.udemy.com/course/the-web-developer-bootcamp/",
    },
    {
        "id": "web-002",
        "title": "React - The Complete Guide 2024",
        "provider": "Udemy",
        "topics": ["react", "javascript", "frontend", "web development", "hooks"],
        "level": "intermediate",
        "careers": ["frontend developer", "web developer", "full stack developer"],
        "duration": "68 hours",
        "rating": 4.7,
        "description": "Master React including Hooks, Redux, React Router, and Next.js.",
        "url": "https://www.udemy.com/course/react-the-complete-guide-incl-redux/",
    },
    {
        "id": "web-003",
        "title": "Full Stack Open",
        "provider": "University of Helsinki",
        "topics": ["full stack", "react", "node", "graphql", "typescript"],
        "level": "intermediate",
        "careers": ["full stack developer", "web developer"],
        "duration": "self-paced",
        "rating": 4.9,
        "description": "Free deep dive into modern web development — React, Node, GraphQL, TS. Highly rated.",
        "url": "https://fullstackopen.com/en/",
    },

    # ── SQL / Databases ─────────────────────────────────────────────────────
    {
        "id": "sql-001",
        "title": "SQL for Data Science",
        "provider": "Coursera / UC Davis",
        "topics": ["sql", "database", "data analysis", "queries"],
        "level": "beginner",
        "careers": ["data analyst", "data scientist", "database administrator"],
        "duration": "4 weeks",
        "rating": 4.6,
        "description": "Learn SQL querying, filtering, joins, and aggregations for data analysis.",
        "url": "https://www.coursera.org/learn/sql-for-data-science",
    },
    {
        "id": "sql-002",
        "title": "The Complete SQL Bootcamp",
        "provider": "Udemy",
        "topics": ["sql", "postgresql", "database", "queries", "joins"],
        "level": "beginner",
        "careers": ["data analyst", "backend developer", "database administrator"],
        "duration": "9 hours",
        "rating": 4.7,
        "description": "Comprehensive SQL course with PostgreSQL — from basics to advanced queries.",
        "url": "https://www.udemy.com/course/the-complete-sql-bootcamp/",
    },

    # ── Cloud ────────────────────────────────────────────────────────────────
    {
        "id": "cloud-001",
        "title": "AWS Certified Cloud Practitioner",
        "provider": "AWS / Udemy",
        "topics": ["cloud", "aws", "cloud computing", "devops"],
        "level": "beginner",
        "careers": ["cloud architect", "devops engineer", "solutions architect"],
        "duration": "12 hours",
        "rating": 4.8,
        "description": "Official AWS certification prep — cloud concepts, services, security, pricing.",
        "url": "https://aws.amazon.com/certification/certified-cloud-practitioner/",
    },
    {
        "id": "cloud-002",
        "title": "Google Cloud Professional Data Engineer",
        "provider": "Google Cloud",
        "topics": ["cloud", "gcp", "data engineering", "bigquery", "dataflow"],
        "level": "advanced",
        "careers": ["data engineer", "cloud architect"],
        "duration": "6 months",
        "rating": 4.6,
        "description": "Prepare for GCP Data Engineer certification — BigQuery, Dataflow, Pub/Sub.",
        "url": "https://cloud.google.com/certification/data-engineer",
    },

    # ── DevOps ───────────────────────────────────────────────────────────────
    {
        "id": "devops-001",
        "title": "Docker and Kubernetes: The Complete Guide",
        "provider": "Udemy",
        "topics": ["devops", "docker", "kubernetes", "containers", "ci/cd"],
        "level": "intermediate",
        "careers": ["devops engineer", "site reliability engineer", "cloud architect"],
        "duration": "21 hours",
        "rating": 4.7,
        "description": "Master Docker containers and Kubernetes orchestration for production deployments.",
        "url": "https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/",
    },
    {
        "id": "devops-002",
        "title": "DevOps Bootcamp: Terraform, AWS, Docker & Kubernetes",
        "provider": "Udemy",
        "topics": ["devops", "terraform", "aws", "docker", "kubernetes", "ci/cd"],
        "level": "intermediate",
        "careers": ["devops engineer", "cloud architect"],
        "duration": "30 hours",
        "rating": 4.6,
        "description": "End-to-end DevOps pipeline from infrastructure as code to container orchestration.",
        "url": "https://www.udemy.com/course/devops-engineering-on-aws/",
    },

    # ── Design ───────────────────────────────────────────────────────────────
    {
        "id": "design-001",
        "title": "UI/UX Design Specialization",
        "provider": "Coursera / California Institute of Arts",
        "topics": ["design", "ui", "ux", "figma", "user research"],
        "level": "beginner",
        "careers": ["ui/ux designer", "product designer", "web designer"],
        "duration": "6 months",
        "rating": 4.6,
        "description": "5-course specialization covering user research, wireframing, and prototyping in Figma.",
        "url": "https://www.coursera.org/specializations/ui-ux-design",
    },

    # ── Excel / Data Analysis ────────────────────────────────────────────────
    {
        "id": "excel-001",
        "title": "Microsoft Excel - Excel from Beginner to Advanced",
        "provider": "Udemy",
        "topics": ["excel", "spreadsheets", "data analysis", "pivot tables", "formulas"],
        "level": "beginner",
        "careers": ["data analyst", "business analyst", "financial analyst"],
        "duration": "19 hours",
        "rating": 4.7,
        "description": "Complete Excel course — formulas, pivot tables, charts, macros, and VBA.",
        "url": "https://www.udemy.com/course/microsoft-excel-2013-from-beginner-to-advanced-and-beyond/",
    },
]
